/*
 important*/
(function(m){var t=function(){};t.test=document.createElement("div");t.randomiseArray=function(k){var x=[],f=[],r;for(r=0;r<k;r++)x[r]=r;for(r=0;r<k;r++){var A=Math.round(Math.random()*(x.length-1));f[r]=x[A];x.splice(A,1)}return f};t.sortArray=function(k,x){var f,r=k.length,A=[];for(f=0;f<r;f++)A[f]=k[x[f]];return A};t.keysrt=function(k,x,f){var r=1;f&&(r=-1);return k.sort(function(A,E){var V=A[x],K=E[x];return r*(V<K?-1:V>K?1:0)})};t.keysrt2=function(k,x,f,r){var A=1;r&&(A=-1);return k.sort(function(E,
V){var K=E[x][f],W=V[x][f];return A*(K<W?-1:K>W?1:0)})};t.getUrlParameter=function(k){var x={};m.location.search.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(f,r,A){x[r]=A});return k?x[k]:x};t.formatTime=function(k){k=Math.round(k,10);var x=Math.floor(k/3600),f=Math.floor((k-3600*x)/60);k=k-3600*x-60*f;if(0<x)return 10>x&&(x="0"+x),10>f&&(f="0"+f),10>k&&(k="0"+k),x+":"+f+":"+k;10>f&&(f="0"+f);10>k&&(k="0"+k);return f+":"+k};t.isScrolledIntoView=function(k){k=k.getBoundingClientRect();var x=k.bottom;
return 0<=k.top+k.height/2&&x-k.height/2<=m.innerHeight};t.sortNumericArray=function(k){k.sort(function(x,f){return x-f})};t.getEvents=function(){var k={};"ontouchstart"in m?(k.downEvent="touchstart mousedown",k.moveEvent="touchmove mousemove",k.upEvent="touchend mouseup"):m.PointerEvent?(k.downEvent="pointerdown",k.moveEvent="pointermove",k.upEvent="pointerup"):(k.downEvent="mousedown",k.moveEvent="mousemove",k.upEvent="mouseup");return k};t.isEmpty=function(k){return 0==k.replace(/^\s+|\s+$/g,"").length};
t.canPlayVorbis=function(){var k=document.createElement("video");return!(!k.canPlayType||!k.canPlayType('video/ogg; codecs="theora, vorbis"').replace(/no/,""))};t.canPlayMp4=function(){var k=document.createElement("video");return!(!k.canPlayType||!k.canPlayType('video/mp4; codecs="avc1.42E01E, mp4a.40.2"').replace(/no/,""))};t.canPlayWebM=function(){var k=document.createElement("video");return!(!k.canPlayType||!k.canPlayType('video/webm; codecs="vp8, vorbis"').replace(/no/,""))};t.audioSupport=function(){return!!document.createElement("audio").canPlayType};
t.canPlayMp3=function(){var k=document.createElement("audio");return!(!k.canPlayType||!k.canPlayType("audio/mpeg;").replace(/no/,""))};t.canPlayWav=function(){var k=document.createElement("audio");return!(!k.canPlayType||!k.canPlayType("audio/wav;").replace(/no/,""))};t.canPlayAac=function(){var k=document.createElement("audio");return!(!k.canPlayType||!k.canPlayType("audio/aac;").replace(/no/,""))};t.canPlayOgg=function(){var k=document.createElement("audio");return!(!k.canPlayType||!k.canPlayType('audio/ogg; codecs="vorbis"').replace(/no/,
""))};t.isMobile=function(){return t.hasPointerEvent&&1<navigator.msMaxTouchPoints?!0:/Android|webOS|iPhone|iPad|iPod|sony|BlackBerry/i.test(navigator.userAgent)};t.isIOS=function(){return navigator.userAgent.match(/(iPad|iPhone|iPod)/g)};t.isAndroid=function(){return-1<navigator.userAgent.indexOf("Android")};t.isiPad=function(){return-1<navigator.userAgent.indexOf("iPad")};t.isiPhoneIpod=function(){var k=navigator.userAgent;return-1<k.indexOf("iPhone")||-1<k.indexOf("iPod")};t.isSafari=function(){return 0<
Object.prototype.toString.call(m.HTMLElement).indexOf("Constructor")};t.isChrome=function(){var k=navigator.userAgent,x=!(0<Object.prototype.toString.call(m.HTMLElement).indexOf("Constructor"))&&"WebkitTransform"in document.documentElement.style;(-1<k.indexOf("iPhone")||-1<k.indexOf("iPod")||-1<k.indexOf("iPad"))&&k.match("CriOS")&&(x=!0);return x};t.parseXML=function(k){if(m.ActiveXObject&&m.GetObject){var x=new ActiveXObject("Microsoft.XMLDOM");x.loadXML(k);return x}if(m.DOMParser)return(new DOMParser).parseFromString(k,
"text/xml");throw Error("No XML parser available");};t.baseUrl=function(){return m.location.href.replace(m.location.hash,"")};t.protocol=function(){return m.location.protocol};t.qualifyURL=function(k){var x=document.createElement("a");x.href=k;return x.href};t.hasLocalStorage=function(){try{return"localStorage"in m&&null!==m.localStorage}catch(k){return!1}};t.validateEmail=function(k){return/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/.test(k)?!0:!1};t.hasDownloadSupport=function(k){return"download"in document.createElement("a")};
t.relativePath=function(k){return/^(?:[a-z]+:)?\/\//i.test(k)};t.hasFullscreen=function(){return t.test.requestFullscreen||t.test.mozRequestFullScreen||t.test.msRequestFullscreen||t.test.oRequestFullscreen||t.test.webkitRequestFullScreen};t.counter=function(k){return 9>k?"0"+(k+1):k+1};t.isNumber=function(k){return!isNaN(parseFloat(k))&&isFinite(k)};t.hmsToSecondsOnly=function(k){k=k.split(":");for(var x=0,f=1;0<k.length;)x+=f*parseInt(k.pop()),f*=60;return x};m.AWPUtils=t})(window);
(function(m,t){m.AWPPlaybackRateSlider=function(k){function x(C){if(!ba){if("touchstart"==C.type){if(C=C.originalEvent.touches,!(C&&0<C.length))return!1}else C.preventDefault();ba=!0;E.on(L.moveEvent,function(B){a:{if("touchmove"==B.type){if(B.originalEvent.touches&&B.originalEvent.touches.length)var M=B.originalEvent.touches;else if(B.originalEvent.changedTouches&&B.originalEvent.changedTouches.length)M=B.originalEvent.changedTouches;else break a;if(1<M.length)break a;M=M[0]}else M=B;B.preventDefault();
f(M);r(M)}}).on(L.upEvent,function(B){a:if(ba){ba=!1;E.off(L.moveEvent).off(L.upEvent);if("touchend"==B.type){if(B.originalEvent.touches&&B.originalEvent.touches.length)var M=B.originalEvent.touches;else if(B.originalEvent.changedTouches&&B.originalEvent.changedTouches.length)M=B.originalEvent.changedTouches;else break a;if(1<M.length)break a;M=M[0]}else M=B;B.preventDefault();f(M);P.hide()}})}return!1}function f(C){C=Math.max(0,Math.min(1,(C.pageX-T.offset().left)/I));A.setValue(C)}function r(C){var B=
C.pageX-T.offset().left;0>B?B=0:B>I&&(B=I);B=Math.max(0,Math.min(1,B/I));if(!AWPUtils.isNumber(B))return!1;B=Z+(va-Z)*B;B=Math.round(10*B)/10;P.text(B);B=W[0].getBoundingClientRect();var M=da[0].getBoundingClientRect();C=parseInt(C.pageX-V.scrollLeft()-B.left-P.outerWidth()/2);var eb=parseInt(M.top-B.top-P.outerHeight());C<M.left-B.left?C=M.left-B.left:C>M.left-B.left+da.outerWidth()-P.outerWidth()&&(C=M.left-B.left+da.outerWidth()-P.outerWidth());P.css({left:C+"px",top:eb+"px"}).show()}var A=this,
E=t(document),V=t(m),K=AWPUtils.isMobile(),W=k.wrapper,ba,P=k.tooltip,T=k.sliderBg,ra=k.sliderLevel,da=k.seekbar,I=T.width(),L=AWPUtils.getEvents(),Z=Number(k.settings.playbackRateMin),va=Number(k.settings.playbackRateMax);da.on(L.downEvent,function(C){x(C);return!1});this.setValue=function(C){AWPUtils.isNumber(I)||(I=T.width());ra.css("width",C*I+"px");C=Z+(va-Z)*C;C=Math.round(10*C)/10;t(A).trigger("AWPPlaybackRateSlider.RANGE_CHANGE",{value:C})};this.setVisual=function(C){C=(C-Z)/(va-Z);AWPUtils.isNumber(I)||
(I=T.width());ra.css("width",C*I+"px")};if(!K){var Ia=function(){da.off(L.moveEvent,r).off("mouseout",Ia);E.off("mouseout",Ia);P.hide()};da.on("mouseover",function(){ba||(da.on(L.moveEvent,r).on("mouseout",Ia),E.on("mouseout",Ia))})}K||this.setVisual(k.settings.playbackRate)}})(window,jQuery);
(function(m,t){m.AWPDownloadManager=function(k){function x(ra,da,I){t.ajax({type:"POST",url:E+"includes/mail.php",data:"mail="+ra+"&title="+da+"&path="+I}).done(function(L){W=!1}).fail(function(L,Z,va){console.log("Send email error: "+L.responseText);f();W=!1});K.css({marginTop:parseInt(-K.height()/2,10)+"px",display:"block"}).stop().animate({opacity:1},{duration:500});T&&clearTimeout(T);T=setTimeout(f,2E3)}function f(){T&&clearTimeout(T);K.stop().animate({opacity:0},{duration:500,complete:function(){K.css("display",
"none")}})}var r=AWPUtils.isMobile();t("body");t(document);var A=k.parent,E=k.settings.sourcePath,V,K,W,ba,P,T;this.setData=function(){V=0<A.find("iframe.awp-dl-iframe").length?A.find("iframe.awp-dl-iframe"):t('<iframe class="awp-dl-iframe"/>').css({position:"absolute",left:"-10000px",display:"none"}).appendTo(A);r&&(K=A.find(".awp-download-confirm"))};this.download=function(ra,da){if(W)return!1;if("file:"==m.location.protocol)return console.log("Downloading files locally is not possible! This requires online server connection."),
!1;var I=ra;var L=da;I.indexOf("\\")&&(I=I.replace(/\\/g,"/"));I.match(/^http([s]?):\/\/.*/)||(I=AWPUtils.qualifyURL(I));r||(L=L.replace(/[^A-Z0-9\-_\.]+/ig,"_"));50<L.length&&(L=L.substr(0,50)+"...");r||/\.(mp3)$/i.test(L)||(L+=".mp3");if(r){W=!0;if(!ba){for(var Z=prompt("Please enter your email address where download link will be sent:");(!AWPUtils.validateEmail(Z)||AWPUtils.isEmpty(Z))&&null!=Z;)Z=prompt("Please enter a valid email address:");(P=Z)&&(ba=!0)}P?x(P,L,I):W=!1}else V.attr("src",E+
"includes/dl.php?path="+I+"&title="+L)};this.setData()}})(window,jQuery);
(function(m,t){m.AWPShareManager=function(k){var x=AWPUtils.isMobile(),f=k.settings,r="https:"==m.location.protocol?"https:":"http:";this.setData=function(){var A=f.facebookAppId||f.fbk;if(AWPUtils.isEmpty(A))console.log("Facebook api key has not been set in settings!");else if(!m.FB&&A&&!document.body.querySelector("#fb-root")){var E=document.createElement("script");E.text="window.fbAsyncInit=function(){FB.init({appId:'"+A+"',status:true,xfbml:true})};(function(e,t,n){var r,i=e.getElementsByTagName(t)[0];if(e.getElementById(n)){return}r=e.createElement(t);r.id=n;r.src='"+
r+"//connect.facebook.net/en_US/all.js';i.parentNode.insertBefore(r,i)})(document,'script','facebook-jssdk')";A=document.createElement("div");A.id="fb-root";document.body.appendChild(A);document.body.appendChild(E)}};this.share=function(A,E,V){var K=(m.screen.width-600)/2,W=(m.screen.height-300)/2,ba=E.description||"",P=E.thumb?AWPUtils.qualifyURL(E.thumb):"";E=E.share;AWPUtils.relativePath(P)||(P=AWPUtils.qualifyURL(P));if("facebook"==A)FB.ui({method:"share",href:encodeURIComponent(E)},function(ra){});
else if("twitter"==A)var T=r+"//twitter.com/share?url="+encodeURIComponent(E)+"&text="+encodeURIComponent(V);else if("tumblr"==A)T=r+"//www.tumblr.com/share/link?url="+encodeURIComponent(E)+"&amp;name="+encodeURIComponent(V)+"&amp;description="+encodeURIComponent(ba);else if("whatsapp"==A){if(x){A=encodeURIComponent(V)+" - "+encodeURIComponent(E);m.location.href="whatsapp://send?text="+A;return}alert(f.whatsAppWarning)}T&&m.open(T,"","menubar=no,toolbar=no,resizable=yes,scrollbars=yes,width=600,height=300,left="+
K+",top="+W)};this.setData()}})(window,jQuery);
(function(m,t){m.AWPPlaylistManager=function(k){function x(){3>f.playlistItems?f.randomPlay=!1:f.randomArr=AWPUtils.randomiseArray(f.playlistItems)}var f=this;this.loopingOn=k.loopingOn;this.randomPlay=k.randomPlay;this.playlistItems;this.lastInOrder=!1;this.counter=-1;this.lastPlayedFromPlaylistClick;this.lastRandomCounter;this.randomPaused=!1;this.randomArr=[];this.playlistSelect=!1;this.setCounter=function(r,A){"undefined"===typeof A&&(A=!0);f.counter=A?f.counter+parseInt(r,10):parseInt(r,10);
if(isNaN(f.counter))alert("AWPPlaylistManager message: No active media, counter = "+f.counter);else if(f.lastInOrder=!1,f.loopingOn){if(f.randomPlay)if(f.counter>f.playlistItems-1){f.counter=f.randomArr[f.playlistItems-1];x();if(f.randomArr[0]==f.counter){var E=f.randomArr.splice(0,1);f.randomArr.push(E)}f.counter=0;t(f).trigger("AWPPlaylistManager.PLAYLIST_END_ALERT")}else 0>f.counter&&(f.counter=f.randomArr[0],x(),f.randomArr[f.playlistItems-1]==f.counter&&(E=f.randomArr.splice(f.playlistItems-
1,1),f.randomArr.unshift(E)),f.counter=f.playlistItems-1);else f.counter>f.playlistItems-1?(f.counter=0,t(f).trigger("AWPPlaylistManager.PLAYLIST_END_ALERT")):0>f.counter&&(f.counter=f.playlistItems-1);t(f).trigger("AWPPlaylistManager.COUNTER_READY")}else f.counter>f.playlistItems-1?(f.counter=f.playlistItems-1,f.lastInOrder=!0):0>f.counter&&(f.counter=0),f.lastInOrder?t(f).trigger("AWPPlaylistManager.PLAYLIST_END"):t(f).trigger("AWPPlaylistManager.COUNTER_READY")};this.getCounter=function(){return f.randomPlay?
f.playlistSelect?f.counter:f.randomArr[f.counter]:f.counter};this.advanceHandler=function(r){f.playlistSelect=!1;f.randomPaused?(f.randomPaused=!1,f.lastRandomCounter+r>f.playlistItems-1?(f.counter=f.playlistItems-1,t(f).trigger("AWPPlaylistManager.COUNTER_READY")):0>f.lastRandomCounter+r?(f.counter=0,t(f).trigger("AWPPlaylistManager.COUNTER_READY")):f.setCounter(f.lastRandomCounter+r,!1)):f.setCounter(r)};this.processPlaylistRequest=function(r){f.playlistSelect=!1;f.randomPlay&&(f.playlistSelect=
!0,f.lastPlayedFromPlaylistClick=r,f.randomPaused||(f.lastRandomCounter=f.counter,f.randomPaused=!0));this.setCounter(r,!1)};this.setPlaylistItems=function(r,A){"undefined"===typeof A&&(A=!0);A&&(f.counter=-1);f.playlistItems=r;f.randomPlay&&x()};this.reSetCounter=function(r){"undefined"===typeof r?f.counter=-1:(r=parseInt(r,10),f.playlistItems?(r>f.playlistItems-1?r=f.playlistItems-1:0>r&&(r=0),f.counter=r):f.counter=-1)};this.setRandom=function(r){f.randomPlay=r;f.randomPlay&&x();if(f.randomPlay){var A=
f.randomArr.length;for(r=0;r<A;r++)if(f.randomArr[r]==f.counter){if(0==r)break;r=f.randomArr.splice(r,1);f.randomArr.unshift(parseInt(r,10));break}f.counter=0}else f.randomPaused?(f.counter=f.lastPlayedFromPlaylistClick,f.randomPaused=!1):f.counter=f.randomArr[f.counter]};this.setLooping=function(r){f.loopingOn=r}}})(window,jQuery);
(function(m){m.fn.awp=function(t){function k(){Object.keys(Ra).forEach(function(w){if(0==w.indexOf("awp-")){var H=w.substr(4).replace(/-([a-z])/g,function(U){return U[1].toUpperCase()});if(w=decodeURIComponent(Ra[w]).replace(/\+/g," "))c.hasOwnProperty(H)?("true"===w?w=!0:"false"===w&&(w=!1),c[H]=w):(w=w.split(",").map(function(U){return U.trim()}),-1<zc.indexOf(H)&&Sa.push({key:H,value:w}))}});if(Sa.length){var a,b,d=Sa.length,g=Sa[0].value.length;for(b=0;b<g;b++){var l={};for(a=0;a<d;a++){var h=
Sa[a];var u=h.value[b];"true"===u?u=!0:"false"===u&&(u=!1);l[h.key]=u;"type"===h.key&&(l.origtype=u)}Db.push(l)}}}function x(){sa.removeClass("awp-is-sticky");var a=sa.height();c.stickyPlayerOpened?sa.css("bottom","0px"):sa.css("bottom",-a+"px");f();setTimeout(function(){sa.css("opacity",1)},50)}function f(){c.stickyPlayerOpened?(q.find(".awp-btn-player-close").show(),q.find(".awp-btn-player-open").hide()):(q.find(".awp-btn-player-close").hide(),q.find(".awp-btn-player-open").show())}function r(){var a=
{activePlaylist:c.activePlaylist,volume:c.volume,activeItem:aa,resumeTime:v.getCurrentTime(),autoPlay:ea};localStorage.setItem(c.continousKey,JSON.stringify(a))}function A(a){if(!Ta){if("touchstart"==a.type){if(a=a.originalEvent.touches,!(a&&0<a.length))return!1}else a.preventDefault();Ta=!0;ma.on(ca.moveEvent,function(b){a:{if("touchmove"==b.type){if(b.originalEvent.touches&&b.originalEvent.touches.length)var d=b.originalEvent.touches;else if(b.originalEvent.changedTouches&&b.originalEvent.changedTouches.length)d=
b.originalEvent.changedTouches;else break a;if(1<d.length)break a;d=d[0]}else d=b;b.preventDefault();V(d);W(d)}}).on(ca.upEvent,function(b){a:if(Ta){Ta=!1;ma.off(ca.moveEvent).off(ca.upEvent);if("touchend"==b.type){if(b.originalEvent.touches&&b.originalEvent.touches.length)var d=b.originalEvent.touches;else if(b.originalEvent.changedTouches&&b.originalEvent.changedTouches.length)d=b.originalEvent.changedTouches;else break a;if(1<d.length)break a;d=d[0]}else d=b;b.preventDefault();V(d);D.hide()}})}return!1}
function E(a){if(!z)return!1;0<c.volume?(Eb=c.volume,c.volume=0):c.volume=Eb;K()}function V(a){Ja?(c.volume=Math.max(0,Math.min(1,(a.pageY-Ka.offset().top)/Ba)),c.volume=1-c.volume):c.volume=Math.max(0,Math.min(1,(a.pageX-Ka.offset().left)/Ba));K()}function K(a){"undefined"!==typeof a&&(c.volume=a);c.useImageWaveform?y&&(y.volume=c.volume):"undefined"!==typeof n&&n.setVolume(c.volume);Ac&&(Ja?Zb.css("height",c.volume*Ba+"px"):Zb.css("width",c.volume*Ba+"px"));Ca.children().hide();0==c.volume?Ca.find(".awp-btn-volume-off").show():
0<c.volume&&.5>c.volume?Ca.find(".awp-btn-volume-down").show():Ca.find(".awp-btn-volume-up").show();"undefined"!==typeof awpVolumeChange&&awpVolumeChange(v,c.instanceName,c.volume)}function W(a){var b=Ja?a.pageY-Ka.offset().top:a.pageX-Ka.offset().left;0>b?b=0:b>Ba&&(b=Ba);b=Math.max(0,Math.min(1,b/Ba));if(!AWPUtils.isNumber(b))return!1;Ja&&(b=1-b);b=parseInt(100*b,10);D.text(b+" %");b=q[0].getBoundingClientRect();var d=fa[0].getBoundingClientRect();if(Ja){var g=parseInt(d.left-b.left-D.outerWidth()/
2+fa.outerWidth()/2);a=parseInt(a.pageY-Ua.scrollTop()-b.top-D.outerHeight()-20);a<d.top-b.top-D.outerHeight()-10?a=d.top-b.top-D.outerHeight()-10:a>d.top-b.top+fa.outerHeight()-D.outerHeight()&&(a=d.top-b.top+fa.outerHeight()-D.outerHeight())}else g=parseInt(a.pageX-Ua.scrollLeft()-b.left-D.outerWidth()/2),a=parseInt(d.top-b.top-D.outerHeight())-10,g<d.left-b.left?g=d.left-b.left:g>d.left-b.left+fa.outerWidth()-D.outerWidth()&&(g=d.left-b.left+fa.outerWidth()-D.outerWidth());0>a+b.top&&(a=parseInt(d.top-
b.top+D.outerHeight()+20));D.css({left:g+"px",top:a+"px"}).show()}function ba(a){var b=a.pageX-qa.offset().left;0>b?b=0:b>qa.width()&&(b=qa.width());b=Math.max(0,Math.min(1,b/qa.width()));if(!AWPUtils.isNumber(b))return!1;parseInt(100*b,10);if(c.useImageWaveform){if(y)var d=y.duration}else d=n.getDuration();if(AWPUtils.isNumber(d)){d=AWPUtils.formatTime(d*b)+" / "+AWPUtils.formatTime(d);D.text(d);d=q[0].getBoundingClientRect();b=qa[0].getBoundingClientRect();a=parseInt(a.pageX-Ua.scrollLeft()-d.left-
D.outerWidth()/2);var g=parseInt(b.top+b.height/2-d.top-D.outerHeight()-25);a<b.left-d.left?a=b.left-d.left:a>b.left-d.left+qa.outerWidth()-D.outerWidth()&&(a=b.left-d.left+qa.outerWidth()-D.outerWidth());0>g+d.top&&(g=parseInt(b.top-d.top+D.outerHeight()+20));D.css({left:a+"px",top:g+"px"}).show()}}function P(a){if(!z)return!1;var b=a.keyCode;if(m(a.target).hasClass("awp-search-filter"))return!0;var d=c.keyboardControls.length;for(a=0;a<d;a++){var g=c.keyboardControls[a];if(b==g.keycode){if("seekBackward"==
g.action)v.seekBackward(c.seekTime);else if("seekForward"==g.action)v.seekForward(c.seekTime);else if("togglePlayback"==g.action)v.togglePlayback();else if("volumeUp"==g.action)c.volume+=.1,1<c.volume&&(c.volume=1),v.setVolume(c.volume);else if("volumeDown"==g.action)c.volume-=.1,0>c.volume&&(c.volume=0),v.setVolume(c.volume);else if("toggleMute"==g.action)v.toggleMute();else if("nextMedia"==g.action)v.nextMedia();else if("previousMedia"==g.action)v.previousMedia();else if("rewind"==g.action)v.seek(0);
else return!0;break}}return!1}function T(a){a.preventDefault();if(!z||c.disableSongSkip)return!1;var b=m(a.currentTarget),d=b.closest(".awp-playlist-item").attr("data-id");if(b.closest(".awp-playlist-item").hasClass("awp-playlist-item-disabled"))return c.togglePlaybackOnPlaylistItem?(Va||(wa=!0),v.togglePlayback()):(v.seek(0),ea||v.playMedia()),!1;Fb=!0;F.processPlaylistRequest(d);"undefined"!==typeof awpPlaylistItemClick&&awpPlaylistItemClick(v,c.instanceName,b,d,a)}function ra(a){a.preventDefault();
if(!z)return!1;a=m(a.currentTarget);if(a.closest(".awp-playlist-item").attr("data-id")==aa)return!1;a.closest(".awp-playlist-item").addClass("awp-playlist-selected");"undefined"!==typeof awpPlaylistItemRollover&&awpPlaylistItemRollover(v,c.instanceName,a)}function da(a){a.preventDefault();if(!z)return!1;a=m(a.currentTarget);if(a.closest(".awp-playlist-item").attr("data-id")==aa)return!1;a.closest(".awp-playlist-item").removeClass("awp-playlist-selected");"undefined"!==typeof awpPlaylistItemRollout&&
awpPlaylistItemRollout(v,c.instanceName,a)}function I(a){if(!z)return!1;a=m(a.currentTarget);a.hasClass("awp-prev-toggle")?v.previousMedia():a.hasClass("awp-playback-toggle")?v.togglePlayback():a.hasClass("awp-skip-backward")?v.seekBackward(c.seekTime):a.hasClass("awp-skip-forward")?v.seekForward(c.seekTime):a.hasClass("awp-next-toggle")?v.nextMedia():a.hasClass("awp-playlist-toggle")?$b.toggle():a.hasClass("awp-loop-toggle")?(xa=!xa,F.setLooping(xa),Gb()):a.hasClass("awp-player-volume")?a.hasClass("awp-toggle-mute")&&
E():a.hasClass("awp-share-toggle")?(fb.is(":visible")&&fb.hide(),gb.toggle()):a.hasClass("awp-share-close")?gb.toggle():a.hasClass("awp-playback-rate-toggle")?(gb.is(":visible")&&gb.hide(),fb.toggle()):a.hasClass("awp-playback-rate-close")?fb.toggle():a.hasClass("awp-random-toggle")?(ya=!ya,F.setRandom(ya),Hb()):a.hasClass("awp-sort-alpha")?(AWPUtils.isEmpty(ha)?ha="title-asc":"title-asc"==ha?ha="title-desc":"title-desc"==ha&&(ha="title-asc"),v.sort(ha),Ib()):a.hasClass("awp-share-item")&&Bc.share(a.attr("data-type").toLowerCase(),
p,La(p))}function L(a){if(!z)return!1;a.preventDefault();if("undefined"!==typeof _AWPTouchManager&&_AWPTouchManager.isDrag())return!1;a=m(a.currentTarget);a.find("i");a.addClass("awp-icon-hover")}function Z(a){if(!z)return!1;a.preventDefault();a=m(a.currentTarget);a.find("i");a.hasClass("awp-random-toggle")&&ya||a.hasClass("awp-loop-toggle")&&xa||a.removeClass("awp-icon-hover")}function va(){Q&&(Q.removeClass("awp-playlist-selected awp-playlist-item-disabled"),"undefined"!==typeof awpPlaylistItemEnabled&&
awpPlaylistItemEnabled(v,c.instanceName,Q),Q=null)}function Ia(a){Q&&va();Q=O.children(".awp-playlist-item[data-id="+a+"]");if(Q.length){Q.addClass("awp-playlist-selected awp-playlist-item-disabled");if(c.usePlaylistScroll&&0<G){if(!Fb)if("mcustomscrollbar"==c.playlistScrollType)if("undefined"!==typeof mCustomScrollbar)setTimeout(function(){"horizontal"==c.playlistScrollOrientation?ta.mCustomScrollbar("scrollTo",parseInt(Q.position().left),{scrollInertia:500}):ta.mCustomScrollbar("scrollTo",parseInt(Q.position().top),
{scrollInertia:500})},1E3);else var b=setInterval(function(){"undefined"!==typeof mCustomScrollbar&&(clearInterval(b),"horizontal"==c.playlistScrollOrientation?ta.mCustomScrollbar("scrollTo",parseInt(Q.position().left),{scrollInertia:500}):ta.mCustomScrollbar("scrollTo",parseInt(Q.position().top),{scrollInertia:500}))},100);else"perfect-scrollbar"==c.playlistScrollType&&setTimeout(function(){"horizontal"==c.playlistScrollOrientation?ta.stop().animate({scrollTop:Q[0].offsetLeft+"px"},{duration:500}):
ta.stop().animate({scrollTop:Q[0].offsetTop+"px"},{duration:500})},1E3);Fb=!1}"undefined"!==typeof awpPlaylistItemDisabled&&awpPlaylistItemDisabled(v,c.instanceName,Q)}}function C(){if(AWPUtils.isScrolledIntoView(q[0]))na=Ma=!0,v.playMedia();else Ua.on(Cc,function(){Jb||(Jb=!0,AWPUtils.isScrolledIntoView(q[0])?(na=Ma=!0,v.playMedia()):Ma||setTimeout(function(){Jb=!1},250))})}function B(){hb=!1;Wa.on("ended",function(){ib()}).on("canplay",function(a){}).on("loadedmetadata",function(){setTimeout(function(){hb||
Wa.trigger("canplay")},1E3)}).on("canplay",function(){if(!hb){hb=!0;if(p.playbackRate)try{y.playbackRate=Number(p.playbackRate)}catch(b){}var a=y.duration;AWPUtils.isNumber(a)&&Da.html(AWPUtils.formatTime(a));K(c.volume);c.autoPlayInViewport&&!Ma&&C();Kb&&(na=!0)}}).on("canplaythrough",function(){c.resumeTime?(y.currentTime=c.resumeTime,delete c.resumeTime):p.start&&(y.currentTime=p.start)}).on("play",function(){ac()}).on("pause",function(){bc()}).on("seeking",function(){var a=y.currentTime,b=y.duration;
Xa.width(za.width()*(a/b))}).on("timeupdate",function(){if(!Ya){var a=y.currentTime,b=y.duration;Lb&&(Na.html(AWPUtils.formatTime(a)),Da.html(AWPUtils.formatTime(b)));Xa.width(za.width()*(a/b));p.end&&a>=p.end&&ib()}}).on("error",function(a){"undefined"!==typeof awpMediaError&&awpMediaError(v,c.instanceName,aa);c.autoAdvanceToNextSongOnError&&v.nextMedia()});y.src=X}function M(a){if(z){if(!Ya){if("touchstart"==a.type){if(a=a.originalEvent.touches,!(a&&0<a.length))return!1}else a.preventDefault();
Ya=!0;ma.on(ca.moveEvent,function(b){a:{if("touchmove"==b.type){if(b.originalEvent.touches&&b.originalEvent.touches.length)var d=b.originalEvent.touches;else if(b.originalEvent.changedTouches&&b.originalEvent.changedTouches.length)d=b.originalEvent.changedTouches;else break a;if(1<d.length)break a;d=d[0]}else d=b;b.preventDefault();eb(d);ba(d)}}).on(ca.upEvent,function(b){a:if(Ya){Ya=!1;ma.off(ca.moveEvent).off(ca.upEvent);if("touchend"==b.type){if(b.originalEvent.touches&&b.originalEvent.touches.length)var d=
b.originalEvent.touches;else if(b.originalEvent.changedTouches&&b.originalEvent.changedTouches.length)d=b.originalEvent.changedTouches;else break a;if(1<d.length)break a;d=d[0]}else d=b;b.preventDefault();eb(d,!0);Ea&&D.hide()}})}return!1}}function eb(a,b,d){b=a.pageX-jb.offset().left;a=jb.width();0>b?b=0:b>a&&(b=a);b=Math.max(0,Math.min(1,b/a));if(y&&!isNaN(y.duration)){var g=y.duration;d=b*g;d>g-2&&(d=g-2);try{y.currentTime=d}catch(l){console.log(l)}}Xa.width(b*a)}function ac(){wa=!1;Ma=!0;if(c.togglePlaybackOnMultipleInstances&&
1<ap_mediaArr.length){var a,b=ap_mediaArr.length;for(a=0;a<b;a++)v!=ap_mediaArr[a].inst&&ap_mediaArr[a].inst.pauseMedia()}Va||("undefined"!==typeof awpMediaStart&&awpMediaStart(v,c.instanceName,aa),Va=!0);Oa.find(".awp-btn-play").hide();Oa.find(".awp-btn-pause").show();Za.find(".awp-btn-play").hide();Za.find(".awp-btn-pause").show();ea=!0;$a&&"undefined"!==typeof ga&&ga("send",{hitType:"event",eventCategory:"Audio Waveform Player: "+c.instanceName,eventAction:"played",eventLabel:"title: "+La(p)+" | time: "+
Math.round(v.getCurrentTime()),nonInteraction:!0});"undefined"!==typeof awpMediaPlay&&awpMediaPlay(v,c.instanceName,Q,aa)}function bc(){Mb();ea=!1;$a&&"undefined"!==typeof ga&&ga("send",{hitType:"event",eventCategory:"Audio Waveform Player: "+c.instanceName,eventAction:"paused",eventLabel:"title: "+La(p)+" | time: "+Math.round(v.getCurrentTime()),nonInteraction:!0});"undefined"!==typeof awpMediaPause&&awpMediaPause(v,c.instanceName,Q,aa)}function Dc(a){kb=m.ajax({url:c.sourcePath+"peaks/peaks.php",
type:"post",data:[{name:"action",value:"awp_read_peaks"},{name:"id",value:a},{name:"path",value:p.peakdir||null}],dataType:"json"}).done(function(b){b.length?(n.backend.peaks=b,lb=!0,c.drawWaveWithoutLoad?n.drawBuffer():n.load(X,n.backend.peaks)):(Nb=!0,p.remote?(Pa.css("opacity",1).html("Loading waveform..."),Ec()):n.load(X))}).fail(function(b,d,g){console.log(b,d,g)})}function Fc(a,b){m.ajax({url:c.sourcePath+"peaks/peaks.php",type:"post",data:[{name:"action",value:"awp_write_peaks"},{name:"peaks",
value:a},{name:"id",value:b},{name:"path",value:p.peakdir||null}],dataType:"json"}).done(function(d){}).fail(function(d,g,l){console.log(d.responseText)})}function Ec(){mb=m.ajax({url:c.sourcePath+"peaks/remote_dl.php",type:"post",data:[{name:"id",value:X},{name:"title",value:p.title},{name:"path",value:p.peakdir||null}],dataType:"json"}).done(function(a){n.getArrayBuffer(a);n.load(a)}).fail(function(a,b,d){console.log(a,b,d)})}function Gc(a){-1!=a.key.indexOf("ebsfm:")&&(a.key=AWPUtils.b64DecodeUnicode(a.key.substr(6)));
var b=c.sourcePath+"includes/aws/aws.php";a={object_key:a.key,bucket:a.path||a.bucket,action:"get_url",expire:c.s3UrlExpireTime,cred:c.s3};console.log(a);m.ajax({type:"GET",url:b,data:a,dataType:"json"}).done(function(d){J="audio";p.path=d;Ob()}).fail(function(d,g,l){console.log(d,g,l);c.autoAdvanceToNextSongOnError&&v.nextMedia()})}function Hc(a){m.ajax({type:"GET",url:c.sourcePath+"includes/aws/aws.php",data:{object_key:a.thumb_key,bucket:a.path||a.bucket,action:"get_url_thumb",expire:c.s3UrlExpireTime,
cred:c.s3},dataType:"json"}).done(function(b){p.thumb=b;cc()}).fail(function(b,d,g){console.log(b,d,g)})}function Ob(){Pb=!1;if(Ic&&p.wav)X=p.wav;else if(Jc&&p.aac)X=p.aac;else if(Kc&&p.mp3)X=p.mp3;else if(p.flac)X=p.flac;else if(p.path)X=p.path;else{alert("No required audio format supplied! Please add mp3 audio format to play!");return}-1!=X.indexOf("ebsfm:")&&(X=atob(X.substr(6)));if(c.useImageWaveform)if(p.peakImage){var a=p.peakImage.load;AWPUtils.relativePath(a)||(a=AWPUtils.qualifyURL(a));var b=
p.peakImage.progress;AWPUtils.relativePath(b)||(b=AWPUtils.qualifyURL(b));dc.css("backgroundImage","url("+a+")");nb.css("backgroundImage","url("+b+")");za.css("display","block");nb.width(za.width());za.removeClass("awp-hidden").addClass("awp-visible");Qb();B(X)}else console.log("No waveform image provided!");else p.peakData?(n.backend.peaks=p.peakData,lb=!0,c.drawWaveWithoutLoad?n.drawBuffer():n.load(X,n.backend.peaks)):Dc(p.peakName||p.title)}function ec(a){oa=!0;fc();ka&&ob();"#"!=a.charAt(0)&&
(a="#"+a);var b=Lc.find(a);if(0==b.length)return alert('Failed to select playlist! Check activePlaylist option in settings. Make sure that element: "'+a+'" exist in awp-playlist-list!'),pb.css("display","none"),oa=!1;c.activePlaylist=a;"undefined"!==typeof awpPlaylistStartLoad&&awpPlaylistStartLoad(v,c.instanceName);ia={};b.attr("data-thumb")&&(ia.thumb=b.attr("data-thumb"));b.attr("data-playback-rate")&&(ia.playbackRate=b.attr("data-playback-rate"));b.attr("data-start")&&(ia.start=b.attr("data-start"));
b.attr("data-end")&&(ia.end=b.attr("data-end"));var d,g;b.find(".awp-playlist-item").each(function(){g=m(this);d=gc(g);pa.push(d)});G=pa.length;N()}function gc(a){var b={};b.origclasses=a.attr("class");b.type=b.origtype=a.attr("data-type");-1!=qb.indexOf(b.type)&&(b.pi_item=a);void 0!=a.attr("data-media-id")&&(b.mediaId=a.attr("data-media-id"));void 0!=a.attr("data-bucket")&&(b.bucket=a.attr("data-bucket"),-1!=b.bucket.indexOf("ebsfm:")&&(b.bucket=AWPUtils.b64DecodeUnicode(b.bucket.substr(6))));void 0!=
a.attr("data-key")&&(b.key=a.attr("data-key"),-1!=b.key.indexOf("ebsfm:")&&(b.key=AWPUtils.b64DecodeUnicode(b.key.substr(6))));void 0!=a.attr("data-mp3")?b.path=a.attr("data-mp3"):void 0!=a.attr("data-wav")?b.path=a.attr("data-wav"):void 0!=a.attr("data-aac")?b.path=a.attr("data-aac"):void 0!=a.attr("data-path")&&(b.path=a.attr("data-path"));b.path&&-1!=b.path.indexOf("ebsfm:")&&(b.path=atob(b.path.substr(6)));void 0!=a.attr("data-peak-load")&&void 0!=a.attr("data-peak-progress")&&(b.peakImage={load:a.attr("data-peak-load"),
progress:a.attr("data-peak-progress")});void 0!=a.attr("data-peak-array")&&(b.peakData=a.attr("data-peak-array").split(","));void 0!=a.attr("data-peak-name")&&(b.peakName=a.attr("data-peak-name"));void 0!=a.attr("data-limit")&&(b.limit=Math.abs(parseInt(a.attr("data-limit"),10)));void 0!=a.attr("data-thumb")?b.thumb=a.attr("data-thumb"):void 0!=a.attr("data-thumb-default")&&(b.thumbDefault=a.attr("data-thumb-default"));void 0!=a.attr("data-title")&&(b.title=a.attr("data-title"));void 0!=a.attr("data-artist")&&
(b.artist=a.attr("data-artist"));void 0!=a.attr("data-album")&&(b.album=a.attr("data-album"));void 0!=a.attr("data-description")&&(b.description=a.attr("data-description"));void 0!=a.attr("data-download")&&(b.download=a.attr("data-download"));void 0!=a.attr("data-id3")&&(b.id3=!0);void 0!=a.attr("data-dir-url")&&(b.dirurl=a.attr("data-dir-url"));void 0!=a.attr("data-peak-dir")&&(b.peakdir=a.attr("data-peak-dir"));ia.start?b.start=ia.start:void 0!=a.attr("data-start")&&(b.start=Math.abs(a.attr("data-start")));
ia.end?b.end=ia.end:void 0!=a.attr("data-end")&&(b.end=Math.abs(a.attr("data-end")));void 0!=a.attr("data-duration")&&(b.duration=Math.abs(a.attr("data-duration")));ia.playbackRate?b.playbackRate=ia.playbackRate:void 0!=a.attr("data-playback-rate")?b.playbackRate=Math.abs(a.attr("data-playback-rate")):b.playbackRate=1;void 0!=a.attr("data-link")&&(b.link=a.attr("data-link"),b.target="_blank",void 0!=a.attr("data-target")&&(b.target=a.attr("data-target")));void 0!=a.attr("data-duration")&&(b.duration=
a.attr("data-duration"));void 0!=a.attr("data-remote")&&(b.remote=!0);void 0!=a.attr("data-sort")&&(b.sort=a.attr("data-sort"));void 0!=a.attr("data-playlist-icons")&&(b.playlistIcons=a.data("playlist-icons"));return b}function N(){Fa++;if(Fa>G-1)Mc();else{var a=pa[Fa],b=pa[Fa].type;if(/^audio$/.test(b))R.push(a),N();else if("podcast"==b)Nc(a);else if("soundcloud"==b)if(la=[],window.SC)rb(!0,a.path);else{Oc();var d=setInterval(function(){hc&&(d&&clearInterval(d),rb(!0,a.path))},100)}else/^folder$/.test(b)?
Pc(a):/^gdrive-folder$/.test(b)?Qc(a):"json"==b?Rc(a):"s3_audio"==b?(R.push(a),N()):"s3_bucket_audio"==b?Sc(a):(console.log("Wrong data-type in playlist! Type = "+b),N())}}function Nc(a){if("file:"==window.location.protocol)console.log("Using Podcast requires server connection!");else{ua=a.limit?a.limit:999999999;var b=Tc+"?url="+encodeURIComponent(a.path),d=ua;m.ajax({url:b,dataType:"json",cache:!1}).done(function(g){g=g.contents.substr(g.contents.indexOf("<?xml"));var l=AWPUtils.parseXML(g),h,u,
w,H=0;m(l).find("image").length&&m(l).find("image").attr("href")?w=m(l).find("image").attr("href"):m(g).find("itunes\\:image").length&&m(g).find("itunes\\:image").attr("href")&&(w=m(g).find("itunes\\:image").attr("href"));w&&w.lastIndexOf("&size=Large")&&(w=w.replace("=Large","=Small"));m(l).find("item").each(function(){if(H>=d)return!1;h=m(this);u=m.extend(!0,{},a);u.type="audio";u.mp3=h.find("enclosure").attr("url");!u.title&&h.find("title").length&&(u.title=h.find("title").text());u.artist||(h.find("author").length?
u.artist=h.find("author").text():h.find("itunes\\:author").length&&(u.artist=h.find("itunes\\:author").text()));h.find("pubDate").length&&(u.date=h.find("pubDate").text());if(!u.description&&h.find("description").length){var U=h.find("description").text(),Y=document.createElement("div");Y.innerHTML=U;u.description=Y.textContent||Y.innerText||""}u.duration||(h.find("itunes\\:duration").length?u.duration=h.find("itunes\\:duration").text():h.find("duration").length&&(u.duration=h.find("duration").text()));
u.thumb||(h.find("image").length&&h.find("image").attr("href")?u.thumb=h.find("image").attr("href"):h.find("itunes\\:image").length&&h.find("itunes\\:image").attr("href")?u.thumb=h.find("itunes\\:image").attr("href"):w&&(u.thumb=w));u.thumb.lastIndexOf("&size=Large")&&(u.thumb=u.thumb.replace("=Large","=Small"));c.createDownloadIconsInPlaylist&&!u.download&&(u.download=u.mp3);h.find("link").length&&!u.link&&c.createLinkIconsInPlaylist&&(u.link=h.find("link").text());R.push(u);H++});N()}).fail(function(g,
l,h){console.log(g,l,h);checkSound()})}}function Oc(){if("file:"==window.location.protocol)console.log("Using SoundCloud requires server connection!");else{c.sck=c.scak[Math.floor(Math.random()*c.scak.length)];var a=document.createElement("script");a.src="https://connect.soundcloud.com/sdk.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b);var d=setInterval(function(){window.SC&&(d&&clearInterval(d),SC.initialize({client_id:c.sck}),hc=!0)},100)}}function rb(a,b){SC.get(a?
"https://api.soundcloud.com/resolve.json?url="+b+"&client_id="+c.sck:b,{limit:ua,linked_partitioning:1},function(d,g){if(g){for(console.log("Error getSoundCloudPage: "+g);la.length;)R.push(la.splice(0,1)[0]);N()}else{if("track"==d.kind)sb(d);else if("playlist"==d.kind){var l,h=d.tracks.length;if(la.length+h>=ua){h=ua-la.length;var u=!0}for(l=0;l<h;l++)sb(d.tracks[l])}else if(d.collection)for(h=d.collection.length,la.length+h>=ua&&(h=ua-la.length,u=!0),l=0;l<h;l++)sb(d.collection[l]);else{if(d.username){l=
d.uri;l=/likes/.test(b)?l+"/likes":/favorites/.test(b)?l+"/favorites":l+"/tracks";rb(!1,l);return}if(m.isArray(d))for(h=d.length,la.length+h>=ua&&(h=ua-la.length,u=!0),l=0;l<h;l++)sb(d[l])}if(d.next_href&&!u)rb(!1,d.next_href);else{for(;la.length;)R.push(la.splice(0,1)[0]);N()}}})}function sb(a){if(a.streamable&&a.stream_url){var b=m.extend(!0,{},pa[Fa]);b.type="audio";a.duration&&(b.duration=a.duration/1E3);-1==a.stream_url.indexOf("?")?b.mp3=a.stream_url+"?client_id="+c.sck:b.mp3=a.stream_url+"&client_id="+
c.sck;c.createDownloadIconsInPlaylist&&!b.download&&a.downloadable&&a.download_url&&(b.download=b.mp3.replace(/\/stream\\?/,"/download"));!b.title&&a.title&&(b.title=a.title);!b.description&&a.description&&(b.description=a.description);!b.thumb&&a.artwork_url&&(b.thumb=a.artwork_url);a.created_at&&(b.date=a.created_at);b.favoritingsCount=parseInt(a.favoritings_count?a.favoritings_count:0,10);b.playbackCount=parseInt(a.playback_count?a.playback_count:0,10);b.hotness=b.favoritingsCount+b.playbackCount;
a.permalink_url&&c.createLinkIconsInPlaylist&&!b.link&&(b.link=a.permalink_url);b.sc_data=a;la.push(b)}}function Sc(a){if("file:"==window.location.protocol)return console.log("Reading folders requires server connection."),!1;m.ajax({type:"GET",url:c.sourcePath+"includes/aws/aws.php",data:{bucket:a.path||a.bucket,action:"list_bucket",cred:c.s3},dataType:"json"}).done(function(b){var d,g=b.length;a.sort&&("filename-asc"==a.sort?AWPUtils.keysrt(b,"filename"):"filename-desc"==a.sort&&AWPUtils.keysrt(b,
"filename",!0));for(d=0;d<g;d++){var l=b[d];if(/mp3|wav|aac|ogg|flac/.test(l)){var h=m.extend(!0,{},a);h.type="s3_audio";h.key=l;h.title=l.substr(0,l.lastIndexOf("."));h.thumb_key=h.title+"."+c.s3ThumbExtension;R.push(h)}}N()}).fail(function(b,d,g){console.log("Error processS3Bucket: "+b.responseText,d,g);N()})}function Rc(a){m.ajax({type:"GET",url:a.path,dataType:"json"}).done(function(b){R=b;var d=R.length;for(b=0;b<d;b++)R[b].peakData&&(R[b].peakData=R[b].peakData.split(","));N()}).fail(function(b,
d,g){console.log("Error processJson: "+b,d,g);N()})}function Pc(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),N(),!1;var b=a.path.replace(/\/\//g,"/"),d=c.sourcePath+"includes/folder_parser.php";b={dir:b,limit:a.limit||1E4};a.id3&&(Rb=Ga=R.length-1);m.ajax({type:"GET",url:d,data:b,dataType:"json"}).done(function(g){a.sort&&("filename-asc"==a.sort?AWPUtils.keysrt(g,"filename"):"filename-desc"==
a.sort?AWPUtils.keysrt(g,"filename",!0):"date-asc"==a.sort?AWPUtils.keysrt(g,"filemtime"):"date-desc"==a.sort&&AWPUtils.keysrt(g,"filemtime",!0));var l,h=g.length;for(l=0;l<h;l++){var u=g[l];var w=m.extend(!0,{},a);w.type="audio";var H=w.dirurl?w.dirurl+u.basename:u.fullpath;w[u.extension]=H;w.title||(w.title=u.filename);c.createDownloadIconsInPlaylist&&!w.download&&(w.download=H);w.share||(w.share=H);c.createLinkIconsInPlaylist&&!w.link&&(w.link=H);R.push(w);Ga++}a.id3?Sb():N()}).fail(function(g,
l,h){console.log("Error processing folder: "+g.responseText);N()})}function Qc(a){if("file:"==window.location.protocol)return console.log("Reading files from folders locally is not possible! This requires online server connection."),N(),!1;var b=c.gDriveAppId||c.gdk;if(AWPUtils.isEmpty(b))return console.log("Google Drive api key has not been set in settings!"),N(),!1;m.ajax({url:"https://www.googleapis.com/drive/v3/files?q='"+a.path+"'+in+parents&pageSize=1000&key="+b,dataType:"jsonp"}).done(function(d){var g,
l=d.files.length,h=[],u=[];for(g=0;g<l;g++){var w=d.files[g];/mp3|mpeg|mpeg3|wav|aac|adts/.test(w.mimeType)?(u.push(w),AWPUtils.keysrt(u,"name")):/jpg|jpeg|png/.test(w.mimeType)&&(h.push(w),AWPUtils.keysrt(h,"name"))}a.sort&&("filename-asc"==a.sort?(AWPUtils.keysrt(u,"name"),AWPUtils.keysrt(h,"name")):"filename-desc"==a.sort&&(AWPUtils.keysrt(u,"name",!0),AWPUtils.keysrt(h,"name",!0)));l=u.length;for(g=0;g<l;g++){w=u[g];d=m.extend(!0,{},a);d.type="audio";var H=w.name.substr(w.name.lastIndexOf(".")+
1);d[H.toLowerCase()]="https://drive.google.com/uc?export=download&id="+w.id;h.length&&!d.thumb&&h[g]&&(d.thumb="https://drive.google.com/uc?export=view&id="+h[g].id);d.title||(d.title=w.name.substr(0,w.name.lastIndexOf(".")));c.createDownloadIconsInPlaylist&&!d.download&&(d.download="https://drive.google.com/uc?export=download&id="+w.id);d.share||(d.share="https://drive.google.com/open?id="+w.id);c.createLinkIconsInPlaylist&&!d.link&&(d.link="https://drive.google.com/open?id="+w.id);R.push(d)}N()}).fail(function(d,
g,l){console.log("Error processing gdrive folder: "+d.responseText);N()})}function Sb(){var a=R[Ga];jsmediatags.read(a.mp3||a.wav||a.aac,{onSuccess:function(b){var d=b.tags;b=d.picture;d.artist&&(a.artist=d.artist);d.title&&(a.title=d.title);d.album&&(a.album=d.album);if(b){d="";var g,l=b.data.length;for(g=0;g<l;g++)d+=String.fromCharCode(b.data[g]);a.thumb="data:"+b.format+";base64,"+window.btoa(d)}Ga--;Ga>Rb?Sb():N()},onError:function(b){console.log("ID3 error: ",b.type,b.info);Ga--;Ga>Rb?Sb():
N()}})}function Mc(){var a,b=Aa?ja:S.length,d=R.length,g=0;for(a=0;a<d;a++){var l=a+b;Aa&&g++;var h=R[a];var u=h.type;if(ab){if(-1!=qb.indexOf(h.origtype))var w=h.pi_item.clone();else h.origclasses||(h.origclasses="awp-playlist-item"),w=m('<div class="'+h.origclasses+'"/>'),delete h.origclasses;var H=m('<div class="awp-playlist-item-content"></div>').on("click",T).prependTo(w);if(!Ea)H.on("mouseenter",ra).on("mouseleave",da);w.attr("data-media-id",h.mediaId);if(-1!=ic.indexOf("thumb")){var U=h.thumb||
h.thumbDefault;if(U){var Y=new Image;Y.className="awp-hidden";Y.onload=function(){this.className="awp-visible awp-thumbimg"};Y.src=U;m('<span class="awp-playlist-thumb"></span>').append(Y).appendTo(H)}}-1!=ic.indexOf("title")&&m('<span class="awp-playlist-title"></span>').appendTo(H);H=m('<div class="awp-playlist-icons"/>').insertAfter(H);h.link&&(U=m('<a class="awp-link awp-playlist-icon" href="'+h.link+'" target="'+(h.target||"_blank")+'" data-tooltip="'+c.linkIconTooltip+'">'+c.iconLink+"</a>"),
H.append(U));h.download&&(U=Uc?m('<a class="awp-download awp-playlist-icon" href="'+h.download+'" download data-tooltip="'+c.downloadIconTooltip+'">'+c.iconDownload+"</a>"):m('<a class="awp-download awp-playlist-icon" href="#" data-tooltip="'+c.downloadIconTooltip+'">'+c.iconDownload+"</a>"),H.append(U));if(h.playlistIcons)for(U=h.playlistIcons.length,b=0;b<U;b++)Y=h.playlistIcons[b],H.append('<a class="awp-playlist-icon awp-icon-'+Y.icon+'" href="'+Y.url+'" target="'+Y.target+'" data-tooltip="'+
Y.title+'">&#x'+Y.icon+"</a>");if(Aa){jc?jc.after(w):Qa?w.appendTo(O):O.children("div").eq(ja).before(w);var jc=w}else w.appendTo(O)}S.splice(l,0,{id:l,type:u,data:h})}ka=O;Tb();Aa||Ub?(l=aa,F.setPlaylistItems(G,!1),ja<=l&&(Qa||F.reSetCounter(l+g)),tb&&F.setCounter(ja,!1)):F.setPlaylistItems(G);kc();ub=!0;"undefined"!==typeof awpPlaylistEndLoad&&awpPlaylistEndLoad(v,c.instanceName,O)}function Tb(){G=S.length;if(ab){var a=0,b,d,g;O.find(".awp-playlist-item").each(function(){d=m(this).attr("data-id",
a);g=d.find(".awp-playlist-title");if(g.length){var l=S[a].data,h="";"undefined"===typeof l.artist||AWPUtils.isEmpty(l.artist)||"undefined"===typeof l.title||AWPUtils.isEmpty(l.title)?"undefined"!==typeof l.artist||"undefined"===typeof l.title||AWPUtils.isEmpty(l.title)?"undefined"===typeof l.artist||AWPUtils.isEmpty(l.artist)||"undefined"!==typeof l.title||(h=l.artist):h=l.title:h=l.artist+c.artistTitleSeparator+l.title;b=h;c.useNumbersInPlaylist?g.html(AWPUtils.counter(a)+c.numberTitleSeparator+
b):g.html(b)}S[a].id=a;a++})}}function kc(){Aa=Ub=!1;pb.css("display","none");oa=!1;z||(z=!0,lc(),ab&&!Vb&&c.usePlaylistScroll&&("mcustomscrollbar"==c.playlistScrollType?ta.mCustomScrollbar({axis:"horizontal"==c.playlistScrollOrientation?"x":"y",theme:c.playlistScrollTheme,scrollInertia:0,mouseWheel:{normalizeDelta:!0,deltaFactor:50,preventDefault:!0},keyboard:{enable:!1},advanced:{autoExpandHorizontalScroll:!0}}):vb=new PerfectScrollbar(ta[0],{wheelSpeed:2,wheelPropagation:!0,minScrollbarLength:30}),
Vb=!0),K(c.volume),AWPUtils.isEmpty(ha)||v.sort(ha),sa.hasClass("awp-is-sticky")&&x(),awpSetupDone(v,c.instanceName));if(!Aa&&0<G){var a=c.activeItem;a>G-1&&(a=G-1);-1<a&&F.setCounter(a,!1)}}function ib(){"undefined"!==typeof awpMediaEnd&&awpMediaEnd(v,c.instanceName,aa);$a&&"undefined"!==typeof ga&&ga("send",{hitType:"event",eventCategory:"Audio Waveform Player: "+c.instanceName,eventAction:"ended",eventLabel:"title: "+La(p),nonInteraction:!0});var a=p.start||0;"next"==c.mediaEndAction?v.nextMedia():
"loop"==c.mediaEndAction?n.play(Number(a)):"rewind"==c.mediaEndAction?(n.pause(),n.seekTo(a/n.getDuration())):"stop"==c.mediaEndAction&&n.pause()}function mc(){z&&"undefined"!==typeof J&&(Q&&va(),wb(),F.reSetCounter())}function wb(){mb&&(mb.abort(),mb=null);kb&&(kb.abort(),kb=null);c.useImageWaveform?(y&&(y.pause(),y.src=""),Wa&&Wa.off("ended canplay canplaythrough loadedmetadata pause play error timeupdate seeking")):"undefined"!==typeof n&&n.empty();Pa.css("opacity",0);Ha.removeClass("awp-visible").addClass("awp-hidden");
dc.empty();nb.empty();Xa.width(0);za.css("display","none").removeClass("awp-visible").addClass("awp-hidden");Lb&&(Na.removeClass("awp-visible").addClass("awp-hidden"),Da.removeClass("awp-visible").addClass("awp-hidden"),Na.html("0:00"),Da.html("0:00"));Wb.empty();Mb();J=null;tb=Va=ea=!1;"undefined"!==typeof awpCleanMedia&&awpCleanMedia(v,c.instanceName)}function ob(){J&&wb();ab&&ka.find(".awp-playlist-item").remove();ka=null;ub=Aa=!1;G=0;Fa=-1;S=[];R=[];pa=[];F.reSetCounter();ha="";Ib();"undefined"!==
typeof awpDestroyPlaylist&&awpDestroyPlaylist(v,c.instanceName,O)}function Qb(){Na.removeClass("awp-hidden").addClass("awp-visible");Da.removeClass("awp-hidden").addClass("awp-visible")}function Mb(){Oa.find(".awp-btn-play").show();Oa.find(".awp-btn-pause").hide();Za.find(".awp-btn-play").show();Za.find(".awp-btn-pause").hide()}function fc(){pb.css("display","block")}function La(a){var b="";"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?
"undefined"!==typeof a.artist||"undefined"===typeof a.title||AWPUtils.isEmpty(a.title)?"undefined"===typeof a.artist||AWPUtils.isEmpty(a.artist)||"undefined"!==typeof a.title||(b=a.artist):b=a.title:b=a.artist+c.artistTitleSeparator+a.title;return b}function nc(){var a=p.playbackRate;bb&&bb.setVisual(a);xb.length&&oc.length?(p.title&&xb.html(p.title),p.artist&&oc.html(p.artist)):xb.length&&(a=La(p),xb.html(a));p.description?pc.html(p.description):pc.html("");p.thumb||"s3_bucket_audio"!=p.origtype&&
"s3_audio"!=p.origtype||!c.getThumbFromBucket?cc():(p.thumb_key||(a=p.key.substr(0,p.key.lastIndexOf(".")),p.thumb_key=a+"."+c.s3ThumbExtension),Hc(p))}function cc(){var a=p.thumb||p.thumbDefault||ia.thumb;if(a&&("soundcloud"==p.origtype&&c.soundCloudThumbQuality&&(a=a.replace("large.jpg",c.soundCloudThumbQuality)),Wb.length)){var b=new Image;b.className="awp-hidden";b.onload=function(){this.className="awp-visible"};b.src=a;Wb[0].appendChild(b)}}function lc(){if(c.breakPointArr){var a,b=c.breakPointArr.length,
d=q.width();for(a=0;a<b;a++){var g=c.breakPointArr[a];d<g?q.addClass("awp-breakpoint-"+g.toString()):q.removeClass("awp-breakpoint-"+g.toString())}}n&&(n.drawer.containerWidth=n.drawer.container.clientWidth,n.drawBuffer(),ea||n.drawer.updateProgress(n.backend.getPlayedPercents()));O.hasClass("awp-masonry")&&v.masonry&&v.masonry.masonry("layout")}function Ib(){cb.find(".awp-btn").hide();ha?cb.find(".awp-sort-alpha-desc").show():cb.find(".awp-sort-alpha-asc").show()}function Gb(){yb.find(".awp-btn").hide();
xa?yb.find(".awp-btn-looping-on").show():yb.find(".awp-btn-looping-off").show()}function Hb(){zb.find(".awp-btn").hide();ya?zb.find(".awp-btn-random-on").show():zb.find(".awp-btn-random-off").show()}var c=m.extend(!0,{},{instanceName:"",sourcePath:"",playlistList:"",activePlaylist:"",resumeTime:null,activeItem:0,volume:.5,autoPlay:!1,preload:"auto",randomPlay:!1,loopingOn:!0,iconLink:'<i class="fa fa-cart-plus"></i>',iconDownload:'<i class="fa fa-download"></i>',mediaEndAction:"loop",sck:"",seekTime:10,
useMediaSession:!0,sortOrder:"",usePlaylistScroll:!1,whatsAppWarning:"Please share this content on mobile device!",allowSeeking:1,playlistScrollType:"mcustomscrollbar",playlistScrollOrientation:"vertical",playlistScrollTheme:"light",fbk:"",scak:"4e6c7139ca2791a89863367ba374a28e r4wruADPCq7iqJomagvYpdehvILa2bgE b972bf0e059078490e8579b43bf95923 64c56d14d1844681f7cca8c61ec0082a 86b6a66bb2d863f5d64dd8a91cd8de94 8da368dc752f739dcf6e4abb8317548d b4bee2a55625cf4ab8e3f7ea1d35e103 0aff03b3b79c2ac02fd2283b300735bd".split(" "),
useNumbersInPlaylist:!1,numberTitleSeparator:".  ",artistTitleSeparator:" - ",pcmLength:100,pcmAccuracy:100,continousKey:"awp-continous-key",playlistItemContent:"title",createDownloadIconsInPlaylist:!1,linkIconTooltip:"Purchase",downloadIconTooltip:"Download",soundCloudThumbQuality:"t300x300.jpg",playbackRateMin:.5,playbackRateMax:2,playbackRate:1,waveformLoaderText:"Loading...",s3ThumbExtension:"jpg",s3UrlExpireTime:"+15 seconds",createLinkIconsInPlaylist:!1,togglePlaybackOnMultipleInstances:!0,
wavesurfer:{waveColor:"#A8DBA8",progressColor:"#ff33ff",barWidth:0,barRadius:0,barGap:1,cursorColor:"#0000ff",cursorWidth:3,height:200},keyboardControls:[{keycode:37,action:"seekBackward"},{keycode:39,action:"seekForward"},{keycode:32,action:"togglePlayback"},{keycode:38,action:"volumeUp"},{keycode:40,action:"volumeDown"},{keycode:77,action:"toggleMute"},{keycode:33,action:"nextMedia"},{keycode:34,action:"previousMedia"},{keycode:82,action:"rewind"}]},t),Ra=AWPUtils.getUrlParameter(),Sa=[],Db=[],
zc="type audio path limit thumb title description artist album download duration date id3 start end link target peak-name peak-array bucket key playback-rate remote sort".split(" ");Ra["awp-instance"]&&decodeURIComponent(Ra["awp-instance"])==c.instanceName&&k();Ra=null;var q=m(this).show(),Lc=m(c.playlistList).hide(),$b=q.find(".awp-playlist-holder"),ta=q.find(".awp-playlist-inner"),O=q.find(".awp-playlist-content"),qc=q.find(".awp-playlist-filter-msg"),cb=q.find(".awp-sort-alpha"),pb=q.find(".awp-preloader"),
D=q.find(".awp-tooltip"),sa=q.find(".awp-player-holder"),Ha=q.find(".awp-waveform"),Wb=q.find(".awp-player-thumb"),xb=q.find(".awp-player-title"),oc=q.find(".awp-player-artist"),pc=q.find(".awp-player-desc"),Na=q.find(".awp-media-time-current"),Da=q.find(".awp-media-time-total");q.find(".awp-player-controls");var Oa=q.find(".awp-playback-toggle"),Za=q.find(".awp-playback-toggle-ex"),Vc=q.find(".awp-player-toggle-ex"),yb=q.find(".awp-loop-toggle"),Ca=q.find(".awp-player-volume"),zb=q.find(".awp-random-toggle");
q.find(".awp-volume-wrapper");var fa=q.find(".awp-volume-seekbar"),Ka=q.find(".awp-volume-bg"),Zb=q.find(".awp-volume-level"),gb=q.find(".awp-share-holder"),Wc=q.find(".awp-share-toggle"),Xc=q.find(".awp-share-close"),Yc=q.find(".awp-playback-rate-toggle"),Zc=q.find(".awp-playback-rate-close"),fb=q.find(".awp-playback-rate-holder"),jb=q.find(".awp-waveform-wrap"),Pa=q.find(".awp-waveform-preloader"),za=q.find(".awp-waveform-img"),dc=q.find(".awp-waveform-img-load"),Xa=q.find(".awp-waveform-img-progress-wrap"),
nb=q.find(".awp-waveform-img-progress"),Ea=AWPUtils.isMobile(),Kc=AWPUtils.canPlayMp3(),Ic=AWPUtils.canPlayWav(),Jc=AWPUtils.canPlayAac(),rc=AWPUtils.isIOS(),sc=AWPUtils.hasLocalStorage(),na=c.autoPlay,Kb=na,wa,xa=c.loopingOn,ya=c.randomPlay,ic=c.playlistItemContent.split(","),tc=c.useMediaSession&&"mediaSession"in navigator&&"file:"!=window.location.protocol,uc=c.useContinousPlayback&&sc,$a=c.useGa&&c.gaTrackingId,ab=$b.length,$c=q.find(".awp-search-filter").length,Lb=Na.length||Da.length,Ac=fa.length,
ha=c.sortOrder,z=!1,oa=!1,v=this;m("body");var Ua=m(window),ma=m(document);AWPUtils.isChrome();AWPUtils.isSafari();var Xb,Uc=AWPUtils.hasDownloadSupport(),ca=AWPUtils.getEvents(),qb=["audio","s3_audio"],vc,Nb,lb,Pb,mb,kb,hb,Ya,Qa,ja,Aa,tb,Ub,Yb,vb,ia={},Ma,Cc="scroll.autoplay"+c.instanceName,Jb,hc,ua,la=[],Tc=c.sourcePath+"includes/ba-simple-proxy.php",aa,Fa=-1,S=[],R=[],pa=[],G=0,ub=!1,ka=null,Q,Va=!1,J,X,ea=!1,p,Fb,Vb,Ga,Rb;c.breakPointArr&&"string"===typeof c.breakPointArr&&(c.breakPointArr=c.breakPointArr.split(","),
AWPUtils.sortNumericArray(c.breakPointArr));c.disableSongSkip&&(c.allowSeeking=0);c.sck&&!AWPUtils.isEmpty(c.sck)&&(c.scak=c.sck.split(",").map(function(a){return a.trim()}));cb.find(".awp-btn-sort-alpha-asc").show();Oa.find(".awp-btn-play").show();"undefined"===typeof window.ap_mediaArr&&(window.ap_mediaArr=[]);ap_mediaArr.push({inst:v,id:c.instanceName});Ea&&(na=!1);c.autoPlayInViewport&&(na=!1);Hb();Gb();Ib();Vc.on("click",function(){var a=sa.height();c.stickyPlayerOpened?sa.stop().animate({bottom:-a+
"px"},{duration:350}):sa.stop().animate({bottom:"0px"},{duration:350});c.stickyPlayerOpened=!c.stickyPlayerOpened;f()});Za.on("click",function(){if(!z)return!1;v.togglePlayback()});$a&&(window.ga||function(a,b,d,g,l,h,u){a.GoogleAnalyticsObject=l;a[l]=a[l]||function(){(a[l].q=a[l].q||[]).push(arguments)};a[l].l=1*new Date;h=b.createElement(d);u=b.getElementsByTagName(d)[0];h.async=1;h.src=g;u.parentNode.insertBefore(h,u)}(window,document,"script","https://www.google-analytics.com/analytics.js","ga"),
ga("create",c.gaTrackingId,"auto"),ga("send","pageview"));!Ea&&D.length&&("static"==q.css("position")&&console.log("player css position is static, therefore tooltip might not work correctly. Please set wrapper css position to other than static if you use tooltip in player."),q.on("mouseenter","[data-tooltip]",function(a){var b=m(this);a=q[0].getBoundingClientRect();var d=b[0].getBoundingClientRect();D.text(b.attr("data-tooltip"));var g=parseInt(d.top-a.top-D.outerHeight());b=parseInt(d.left-a.left-
D.outerWidth()/2+b.outerWidth()/2);var l=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;0>b+a.left?b=parseInt(d.left-a.left+15):b+a.left+D.outerWidth()>l&&(b=parseInt(d.left+d.width-a.left-D.outerWidth()));0>g+a.top&&(g=parseInt(d.top-a.top+D.outerHeight()+15));D.css({left:b+"px",top:g+"px"}).show()}).on("mouseleave","[data-tooltip]",function(a){D.hide()}));var wc=q.find(".awp-playback-rate-seekbar");q.find(".awp-playback-rate-min").html(c.playbackRateMin);q.find(".awp-playback-rate-max").html(c.playbackRateMax);
if(wc.length){var bb=new AWPPlaybackRateSlider({settings:c,wrapper:q,seekbarHolder:q.find(".awp-playback-rate-wrap"),seekbar:wc,sliderBg:q.find(".awp-playback-rate-bg"),sliderLevel:q.find(".awp-playback-rate-level"),tooltip:D});m(bb).on("AWPPlaybackRateSlider.RANGE_CHANGE",function(a,b){v.setPlaybackRate(b.value)})}if($c)q.find(".awp-search-filter").on("keyup",function(){var a=m(this).val().toLowerCase(),b,d=0;for(b=0;b<G;b++){var g=O.find(".awp-playlist-item").eq(b);var l="";g.find(".awp-playlist-title").length&&
(l+=g.find(".awp-playlist-title").html().toLowerCase());-1<l.indexOf(a)?g.removeClass("awp-filter-hidden").show():(g.addClass("awp-filter-hidden").hide(),d++)}d==G?(qc.show(),Yb=!1):(qc.hide(),Yb=!0)});var ad=new AWPDownloadManager({settings:c,parent:q});O.on("click",".awp-download",function(){e.preventDefault();var a=m(this).closest(".awp-playlist-item").attr("data-id");a=S[a].data;var b=La(a);$a&&"undefined"!==typeof ga&&ga("send",{hitType:"event",eventCategory:"Audio Waveform Player: "+c.instanceName,
eventAction:"downloaded",eventLabel:"title: "+b,nonInteraction:!0});"undefined"!==typeof a.download&&ad.download(a.download,b)});var Bc=new AWPShareManager({settings:c}),F=new AWPPlaylistManager({randomPlay:c.randomPlay,loopingOn:c.loopingOn});m(F).on("AWPPlaylistManager.COUNTER_READY",function(){J&&wb();aa=F.getCounter();p=S[aa].data;J=p.type;ab&&Ia(aa);nc();"s3_audio"==J?Gc(p):Ob();"undefined"!==typeof awpItemTriggered&&awpItemTriggered(v,c.instanceName,aa)}).on("AWPPlaylistManager.PLAYLIST_END AWPPlaylistManager.PLAYLIST_END_ALERT",
function(){"undefined"!==typeof awpPlaylistEnd&&awpPlaylistEnd(v,c.instanceName)});uc?((window.attachEvent||window.addEventListener)(rc?"pagehide":"beforeunload",function(a){window.event&&(window.event.cancelBubble=!0);if(!z||!J)return!1;r()}),rc&&document.addEventListener("unload",function(a){r()})):localStorage.removeItem(c.continousKey);tc&&(navigator.mediaSession.setActionHandler("play",function(){v.playMedia()}),navigator.mediaSession.setActionHandler("pause",function(){v.pauseMedia()}),navigator.mediaSession.setActionHandler("previoustrack",
function(){v.previousMedia()}),navigator.mediaSession.setActionHandler("nexttrack",function(){v.nextMedia()}),navigator.mediaSession.setActionHandler("seekbackward",function(){v.seekBackward()}),navigator.mediaSession.setActionHandler("seekforward",function(){v.seekForward()}));var Ja=fa.hasClass("awp-vertical")?!0:!1,Eb=.5,Ba=void 0!=c.volumeSize?c.volumeSize:Ja?Ka.height():Ka.width(),Ta;0>c.volume?c.volume=0:1<c.volume&&(c.volume=1);0!=c.volume&&(Eb=c.volume);if(Ca.hasClass("awp-volume-toggable"))Ca.on("click",
function(){E(!0)});if(fa.length)fa.on(ca.downEvent,function(a){A(a);return!1});if(D.length&&!Ea){var Ab=function(){fa.off(ca.moveEvent,W).off("mouseout",Ab);ma.off("mouseout",Ab);D.hide()};fa.on("mouseover",function(){Ta||(fa.on(ca.moveEvent,W).on("mouseout",Ab),ma.on("mouseout",Ab))})}if(function(){var a=!1,b=document.URL,d=b.indexOf("://")+3,g=b.indexOf("/",d);b=b.substring(d,g).split(".");d=[1059,653,969,1728];g=[];var l,h,u=b.length;for(l=0;l<u;l++){var w=b[l];var H=w.length;var U=h=0;for(h;h<
H;h++){var Y=w.charAt(h);U+=Y.charCodeAt(0)}g.push(U)}l=0;u=g.length;H=d.length;l;a:for(;l<u;l++)for(h=0,h;h<H;h++)if(g[l]==d[h]){a=!0;break a}return a}()){var qa=c.useImageWaveform?jb:Ha;if(!Ea){var Bb=function(){qa.off(ca.moveEvent,ba).off("mouseout",Bb);ma.off("mouseout",Bb);D.hide()};qa.on("mouseover",function(){qa.on(ca.moveEvent,ba).on("mouseout",Bb);ma.on("mouseout",Bb)})}if(c.useKeyboardNavigationForPlayback&&c.keyboardControls.length)if(Array.isArray(c.keyboardControls)||(c.keyboardControls=
c.keyboardControls.split(";")),c.useGlobalKeyboardControls)ma.on("keydown.awp",function(a){return P(a)});else q.hover(function(){ma.on("keydown",function(a){return P(a)})},function(){ma.off("keydown")});var xc=[q.find(".awp-next-toggle"),q.find(".awp-prev-toggle"),q.find(".awp-playlist-toggle"),q.find(".awp-share-item"),cb,Ca,Oa,yb,zb,Wc,Xc,Yc,Zc,q.find(".awp-skip-backward"),q.find(".awp-skip-forward")],bd=xc.length,Cb;for(Cb=0;Cb<bd;Cb++){var cd=m(xc[Cb]).css("cursor","pointer").on("click",I);if(!Ea)cd.on("mouseenter",
L).on("mouseleave",Z)}if("image"==c.iconType)q.on("mouseenter",".awp-contr-btn, .awp-playlist-icon",function(){var a=m(this);void 0!=a.find("img:visible").attr("data-icon-hover")&&(a=a.find("img:visible"),a.attr("data-icon-normal",a.attr("src")),a.attr("src",a.attr("data-icon-hover")))}).on("mouseleave",".awp-contr-btn, .awp-playlist-icon",function(){var a=m(this);void 0!=a.find("img:visible").attr("data-icon-hover")&&(a=a.find("img:visible"),a.attr("src",a.attr("data-icon-normal")))});if(c.useImageWaveform){Ha.remove();
Pa.remove();var Wa=m(document.createElement("audio")).attr("preload",c.preload);var y=Wa[0];jb.on(ca.downEvent,function(a){if(c.disableSeekbar||c.disableSongSkip||!J)return!1;M(a);return!1})}else{window.AudioContext=window.AudioContext||window.webkitAudioContext;var yc=new AudioContext;"suspended"===yc.state&&(Kb&&(wa=!0),Mb(),ea=!1,"undefined"!==typeof awpAutoplayFail&&awpAutoplayFail(v,c.instanceName,aa));var n=WaveSurfer.create({container:Ha[0],backend:"MediaElement",audioContext:yc,interact:c.allowSeeking,
pixelRatio:1,hideScrollbar:!0,waveColor:c.wavesurfer.waveColor,progressColor:c.wavesurfer.progressColor,barWidth:c.wavesurfer.barWidth,barRadius:c.wavesurfer.barRadius,barGap:c.wavesurfer.barGap,cursorColor:c.wavesurfer.cursorColor,cursorWidth:c.wavesurfer.cursorWidth,height:c.wavesurfer.height});n.on("loading",function(a){a=c.waveformLoaderText+" "+a.toString()+"%";Pa.css("opacity",1).html(a)});n.on("finish",function(a){ib()});n.on("error",function(a){"undefined"!==typeof awpMediaError&&awpMediaError(v,
c.instanceName,aa);c.autoAdvanceToNextSongOnError&&v.nextMedia()});n.on("audioprocess",function(a){a=n.getCurrentTime();var b=n.getDuration();Lb&&(Na.html(AWPUtils.formatTime(a)),Da.html(AWPUtils.formatTime(b)));p.end&&a>=p.end&&ib()});n.on("play",function(){ac()});n.on("pause",function(){bc()});n.on("interaction",function(){wa=!1});n.on("ready",function(){if(!Pb){Pb=!0;vc||(vc=!0,Ha.find("audio").remove());n.setVolume(c.volume);c.resumeTime&&(p.start=c.resumeTime,delete c.resumeTime);var a=p.start||
0;if(p.end)var b=p.end;p.playbackRate&&n.setPlaybackRate(p.playbackRate);na&&(b?n.play(a,b):n.play(a));c.autoPlayInViewport&&!Ma&&C();Kb&&(na=!0)}});n.on("waveform-ready",function(){Nb&&(n.exportPCM(c.pcmLength,c.pcmAccuracy,!0).then(function(a){Array.isArray(a)?a=a.toString():("["==a.charAt(0)&&(a=a.substr(1)),"]"==a.charAt(a.length-1)&&(a=a.substr(0,a.length-1)));Fc(a,p.peakName||p.title)}),Nb=!1);Pa.css("opacity",0);c.useImageWaveform||Ha.removeClass("awp-hidden").addClass("awp-visible");Qb()});
n.on("redraw",function(){lb&&(Pa.css("opacity",0),c.useImageWaveform||Ha.removeClass("awp-hidden").addClass("awp-visible"),Qb(),lb=!1)})}Ua.resize(function(){if(!z)return!1;Xb&&clearTimeout(Xb);Xb=setTimeout(lc,150);if(c.useImageWaveform&&(nb.width(za.width()),y)){var a=y.currentTime,b=y.duration;Xa.width(za.width()*(a/b))}});this.loadPlayMedia=function(){if(!z||!J||!p)return!1;X&&n.backend.peaks&&n.load(X,n.backend.peaks,!0)};this.playMedia=function(){if(!z||!J||ea)return!1;if(c.useImageWaveform){if(y){var a=
y.play();void 0!==a&&a.then(function(){})["catch"](function(b){})}}else wa&&(wa=!1,n.seekTo(.01)),"undefined"!==typeof n&&n.play()};this.pauseMedia=function(){if(!z||!J||!ea)return!1;c.useImageWaveform?y&&y.pause():"undefined"!==typeof n&&n.pause()};this.checkMedia=function(a){if(!z||!J)return!1;a=a.toLowerCase();ea&&"pause"==a&&(c.useImageWaveform?y&&y.pause():"undefined"!==typeof n&&n.pause())};this.togglePlayback=function(){if(!z||!J)return!1;if(c.useImageWaveform){if(y)if(y.paused){var a=y.play();
void 0!==a&&a.then(function(){})["catch"](function(d){})}else y.pause()}else if("undefined"!==typeof n)if(!Va&&c.drawWaveWithoutLoad&&n.backend.peaks)na=!0,v.loadPlayMedia();else{if(!AWPUtils.isNumber(n.getDuration()))return!1;if(wa)if(wa=!1,p.start||p.end){a=p.start||0;if(p.end)var b=p.end;b?n.play(a,b):n.play(a)}else n.seekTo(.01);ea?n.pause():n.play()}};this.stop=function(){if(!z||!J)return!1;c.useImageWaveform?y&&y.pause():("undefined"!==typeof n&&n.stop(),ea=!1)};this.nextMedia=function(){if(!z||
!ka||c.disableSongSkip)return!1;if(c.usePlaylist&&Yb){var a=O.find(".awp-playlist-item-selected").nextAll(".awp-playlist-item:not(.awp-filter-hidden)").filter(":first");a.length?(a=a.attr("data-id"),F.setCounter(a,!1)):F.advanceHandler(1,!0)}else F.advanceHandler(1,!0);F.advanceHandler(1,!0)};this.previousMedia=function(){if(!z||!ka||c.disableSongSkip)return!1;F.advanceHandler(-1,!0)};this.loadMedia=function(a,b){if(!z||oa||!ka)return!1;if("title"==a){var d;for(d=0;d<G;d++)if(b==S[d].data.title){b=
d;var g=!0;break}if(!g)return alert('Track with title "'+b+'" doesnt exist. LoadMedia failed.'),!1}else if("counter"==a){if(0>b||b>G-1)return alert('Invalid track number. Track number  "'+b+'" doesnt exist. LoadMedia failed.'),!1}else if("id"==a&&(d=O.find(".awp-playlist-item[data-media-id="+b+"]"),b=O.children(".awp-playlist-item").index(d),void 0==b||!b||-1==b))return alert("No media with ID to load! LoadMedia failed."),!1;F.processPlaylistRequest(b)};this.loadPlaylist=function(a){if(!z||oa)return!1;
if("undefined"===typeof a||AWPUtils.isEmpty(a))return alert("loadPlaylist method requires id parameter. loadPlaylist failed."),!1;if(c.activePlaylist==a)return!1;ec(a)};this.addTrack=function(a,b,d,g){if(!z||oa)return!1;if("undefined"===typeof a)return alert("addTrack method requires format parameter. AddTrack failed."),!1;if("undefined"===typeof b)return alert("addTrack method requires track parameter. AddTrack failed."),!1;tb=!1;"undefined"!==typeof d&&(tb=d);d=1;var l=!1;if("string"!==typeof b&&
"[object Object]"!==Object.prototype.toString.call(b))if("[object Array]"===Object.prototype.toString.call(b))d=b.length,l=!0;else return alert("addTrack method requires track as string, object or array parameter. AddTrack failed."),!1;ja=g;Qa=!1;Aa=!0;if(ka)if("undefined"!==typeof ja){if(0>ja||ja>G)return alert('Invalid position to insert track to. Position number "'+g+'" doesnt exist. AddTrack failed.'),!1;ja==G&&(Qa=!0)}else Qa=!0,ja=G;else{if("undefined"!==typeof ja){if(0!=ja)return alert('Invalid position to insert track to. Position number "'+
g+'" doesnt exist. AddTrack failed.'),!1}else ja=0;Qa=!0}oa=!0;fc();ub=!1;Ub=!0;Fa=-1;R=[];pa=[];for(g=0;g<d;g++){var h=l?b[g]:b;if("html"==a){h=m(h);var u=m("<div>").append(h.clone()).html();h=document.createElement("div");h.innerHTML=u;h=m(h.firstChild);h=gc(h)}pa.push(h)}G=pa.length;ka=O;N()};this.inputAudio=function(a){if(!z||oa)return!1;if("undefined"===typeof a)return alert("inputAudio method requires data parameter. inputAudio failed."),!1;Q&&va();0<G&&F.reSetCounter();p=a;J=a.type;if(-1==
qb.indexOf(J))return alert("inputAudio method supports tracks that dont require processing: "+qb),!1;nc();tc&&(navigator.mediaSession.metadata=new MediaMetadata({title:p.title,artist:p.artist||"",album:p.album||"",artwork:[{src:p.thumb||p.thumbDefault||ia.thumb||""}]}));na=!0;Ob()};this.removeTrack=function(a){if(!z||oa||!ka)return!1;if("undefined"===typeof a)return alert("removeTrack method requires id parameter. removeTrack failed."),!1;if("string"===typeof a){var b,d=!1;for(b=0;b<G;b++)if(a==S[b].data.title){a=
b;d=!0;break}if(!d)return alert('Track with title "'+a+'" doesnt exist. RemoveTrack failed.'),!1}else if("number"===typeof a){if(a=parseInt(a,10),0>a||a>G-1)return alert('Invalid id number. Track number  "'+a+'" doesnt exist. RemoveTrack failed.'),!1}else return alert("removeTrack method requires either a id number or a track title to remove. removeTrack failed."),!1;S[a]?(O.children(".awp-playlist-item").eq(a).remove(),S.splice(a,1),Tb(),0<G?(b=F.getCounter(),a==b?(wb(),F.setPlaylistItems(G)):(F.setPlaylistItems(G,
!1),a<b&&F.reSetCounter(F.getCounter()-1))):ob()):alert('RemoveTrack with id "'+a+'" failed.')};this.sort=function(a,b){if(!z||!ka)return!1;if("undefined"===typeof a)return console.log("Sort method requires type parameter. Sort method failed."),!1;if(ha==l)return!1;var d=O.children(".awp-playlist-item"),g=d.length,l=a.toLowerCase();if(2>g)return!1;if("title-asc"==l){AWPUtils.keysrt2(S,"data","title");var h;g=[];for(h=0;h<G;h++)g.push(S[h].id)}else if("title-desc"==l)for(AWPUtils.keysrt2(S,"data",
"title",!0),g=[],h=0;h<G;h++)g.push(S[h].id);else if("random"==l)g=AWPUtils.randomiseArray(g),S=AWPUtils.sortArray(S,g);else return console.log("Sort method requires type parameter. Sort method failed."),!1;ha=l;l=F.getCounter();O.append(m.map(g,function(u){return d[u]}));-1!=l&&(l=O.children(".awp-playlist-item[data-id='"+l+"']").index(),F.reSetCounter(l));Tb()};this.destroyInstance=function(){ob();mc();"undefined"!==typeof n&&n.destroy();c.usePlaylistScroll&&("mcustomscrollbar"==c.playlistScrollType?
"undefined"!==typeof mCustomScrollbar&&ta.mCustomScrollbar("destroy"):"perfect-scrollbar"==c.playlistScrollType&&vb&&(vb.destroy(),vb=null),Vb=!1)};this.destroyMedia=function(){if(!z)return!1;mc()};this.destroyPlaylist=function(){if(!z||!ka)return!1;ob()};this.setPlaybackRate=function(a){if(!z||!J)return!1;c.playbackRate=a;bb&&bb.setVisual(a);if(c.useImageWaveform){if(y)try{y.playbackRate=Number(a)}catch(b){}}else"undefined"!==typeof n&&n.setPlaybackRate(a)};this.toggleRandom=function(a){if(!z||"undefined"===
typeof F)return!1;ya="undefined"!==typeof a?a:!ya;F.setRandom(ya);Hb()};this.toggleLoop=function(a){if(!z||"undefined"===typeof F)return!1;xa="undefined"!==typeof a?a:!xa;F.setLooping(xa);Gb()};this.setVolume=function(a){if(!z)return!1;0>a?a=0:1<a&&(a=1);c.volume=a;K()};this.getVolume=function(){return z?c.volume:!1};this.toggleMute=function(){if(!z)return!1;E()};this.seek=function(a){if(!z||!J||c.disableSongSkip||!c.allowSeeking)return!1;if(c.useImageWaveform){if(y)try{y.currentTime=a}catch(b){console.log(b)}}else"undefined"!==
typeof n&&n.seekTo(a/n.getDuration())};this.seekBackward=function(a){if(!z||!J)return!1;a=a||c.seekTime;a=parseInt(a,10);if(c.useImageWaveform){if(y)try{y.currentTime=Math.max(y.currentTime-a,0)}catch(b){console.log(b)}}else"undefined"!==typeof n&&(a=Math.max(n.getCurrentTime()-a,0),n.seekTo(a/n.getDuration()))};this.seekForward=function(a){if(!z||!J||!c.allowSeeking)return!1;a=a||c.seekTime;a=parseInt(a,10);if(c.useImageWaveform){if(y)try{y.currentTime=Math.min(y.currentTime+a,y.duration)}catch(b){console.log(b)}}else"undefined"!==
typeof n&&(a=Math.min(n.getCurrentTime()+a,n.getDuration()),n.seekTo(a/n.getDuration()))};this.getCurrentTime=function(){if(!z||!J)return!1;var a;if(c.useImageWaveform)return y?y.currentTime:0;"undefined"!==typeof n&&(a=n.getCurrentTime());return a};this.getDuration=function(){if(!z||!J)return!1;var a;if(c.useImageWaveform){if(y)return y.duration}else return"undefined"!==typeof n&&(a=n.getDuration()),a};this.getSetupDone=function(){return z};this.getPlaylistTransition=function(){return oa};this.getPlaylistLoaded=
function(){return ub};this.getMediaPlaying=function(){return z?ea:!1};this.getPlaylistLength=function(){return z?AWPUtils.isNumber(G)?G:0:!1};this.getPlaylistItems=function(){if(!z)return!1;var a=[];O.find(".awp-playlist-item").each(function(){a.push(m(this))});return a};this.getPlaylistData=function(){return S||null};this.getCurrMediaData=function(){return z?p:!1};this.getSettings=function(){return z?c||null:!1};this.getInstanceName=function(){return z?c.instanceName:!1};if(sc&&c.continousKey)if(!uc)localStorage.removeItem(c.continousKey);
else if(localStorage.getItem(c.continousKey)){var db=JSON.parse(localStorage.getItem(c.continousKey));c.activePlaylist=db.activePlaylist;c.resumeTime=db.resumeTime;c.volume=db.volume;c.activeItem=db.activeItem;na=c.autoPlay=db.autoPlay;localStorage.removeItem(c.continousKey)}setTimeout(function(){Db.length?(console.log("loading query playlist"),oa=!0,pb.show(),"undefined"!==typeof awpPlaylistStartLoad&&awpPlaylistStartLoad(v,c.instanceName),pa=Db,G=pa.length,N()):AWPUtils.isEmpty(c.activePlaylist)?
kc():ec(c.activePlaylist)},50);return this}}})(jQuery);
